name: Sync Fork

on:
  schedule:
    - cron: '0 2 * * *'   # every day at 2 AM UTC
  workflow_dispatch:        # lets you trigger manually from Actions tab

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Git
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Sync upstream -> fork
        run: |
          git remote add upstream https://github.com/epfml/ML_course
          git fetch upstream
          git checkout main
          git merge upstream/main --no-edit --allow-unrelated-histories || true
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} main
